name: 'PHP_CodeSniffer Check with Annotations'
description: 'PHPCS checker with auto annotations out of the box'
author: 'Ilya Chekalsky'
inputs:
  enable_warnings:
    description: 'Enable checking for warnings (-w)'
    required: false
    default: ''
  enable_phpcbf:
    description: 'Run PHPCBF with the prescribed standard'
    requred: false
    default: ''
  paths:
    description: 'Path(s) to check (space separated)'
    required: false
    default: '.'
  excludes:
    description: 'Path(s) to excludes (space separated)'
    required: false
    default: ''
  standard:
    description: 'Standard to use (default to WordPress)'
    required: false
    default: 'WordPress'
  standard_repo:
    description: 'Public (git) repository URL of the coding standard'
    required: false
    default: ''
  repo_branch:
    description: 'Repository branch'
    required: false
    default: 'master'
  phpcs_bin_path:
    description: 'PHPCS bin path'
    required: false
    default: 'phpcs'
  use_local_config:
    description: 'Use local config if available'
    required: false
    default: 'false'
  extra_args:
    description: 'Passing extra arguments to the phpcs command'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zap'
  color: 'purple'
